server:
  port: 8005

# NOTE: use hierarchy structure
# spring data source properties
spring:
  datasource:
    jdbc-url: ${JDBC_DATABASE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    pool-size: 30
    maxActive: 20
    maxIdle: 5
    minIdle: 2
    initialSize: 5
  jpa:
    show-sql: true
    hibernate:
      open-in-view: false
      generate-ddl: true
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB