server:
  port: 8005

# spring datasource properties
spring:
  datasource:
    jdbc-url: ${JDBC_DATABASE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    pool-size: 30
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5

jpa:
  show-sql: trye
  generate-ddl: true
  hibernate:
    ddl-auto: create
    database: userdb