# default database properties
database:
  host: localhost
  port: 5432
  username: postgres
  password: root

# spring datasource properties
spring:
  datasource:
    jdbc-url: jdbc:postgres://fhehmrcgzmpjhn:30af34cb97bae5f97d6c6a13ceb6a74d6511d6f16ec77bdaadab09a398857784@ec2-35-169-254-43.compute-1.amazonaws.com:5432/defp5q4qsijggp
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
    pool-size: 30
    jpa:
      show-sql: trye
      generate-ddl: true
      hibernate:
        ddl-auto: create
      database: userdb