server:
  port: 8005

# default database properties
database:
  host: localhost
  port: 5432
  username: postgres
  password: root

# spring datasource properties
spring:
  datasource:
    jdbc-url: ${JDBC_DATABASE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    pool-size: 30
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5

