server:
  port: 8005

java:
  runtime:
    version: 11
# NOTE: use hierarchy structure
# spring data source properties
spring:
  datasource:
    jdbc-url: ${JDBC_DATABASE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
    pool-size: 30
    maxActive: 20
    maxIdle: 5
    minIdle: 2
    initialSize: 5
  jpa:
    show-sql: true
    hibernate:
      open-in-view: false
      generate-ddl: true
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

application:
  jwt:
    secretKey: "HETHIyK0NjMUGRxvEpIir8mG46yOEsj1NsonLPdZ3to8RzwBgfKqMd1YQeVivr-bYpLPPg0zCy1y44ND2o86VhqYTaIWFAcG-W9aLnVqFTiqOsDXDuh-i8T8xaoiqzpH4PzRsYFy_Ma5LmRfHmVFE2aez-K0klFLK5O-4UKVl0NVTzjzAKF7F7M7HEp95nwUNZf-8592C1XyA6u_chiEAK_l1awEwFzpFlB7Bl7dG2xBgjTIhd4K1lw3fTT2x6dcOmdSNlShGJ3n0njaCf14Om6DIdketVTeTrKIam59MKeue_sqaJWZoW2zzT3rDUtYzEnZrXqF_bVBe7-5Eg8wOQ"
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14