# default database properties
database:
  host: localhost
  port: 5432
  username: postgres
  password: root

# heroku datasource properties
dbheroku:
  datasource:
  jdbc-url: jdbc:postgresql://${database.host}:${database.port}/
  driver-class-name: org.postgresql.Driver
  pool-size: 30
  maxActive: 10
  maxIdle: 5
  minIdle: 2
  initialSize: 5
  removeAbandoned: true
  jpa:
    show-sql: trye
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database: userdb

# spring datasource properties
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    pool-size: 30
    jpa:
      show-sql: trye
      generate-ddl: true
      hibernate:
        ddl-auto: create
      database: userdb